apiVersion: v2
name: camunda-bpm-platform
description: |
  Helm Chart for Camunda BPM Platform (Engines, Tasklist, Cockpit, etc).
type: application
version: 1.1.0
appVersion: latest
keywords:
  - bpm
  - bpmn
  - camunda-bpm-platform
  - camunda-engine
  - dmn
  - process-engine
  - workflow
icon: https://docs.camunda.org/get-started/img/Camunda-Circle.svg
home: https://camunda.com
sources:
  - https://github.com/camunda-community-hub/camunda-helm/tree/main/charts/camunda-bpm-platform
  - https://github.com/camunda/docker-camunda-bpm-platform
  - https://github.com/camunda/camunda-bpm-platform
maintainers:
  - name: aabouzaid
    url: https://tech.aabouzaid.com
annotations:
  artifacthub.io/links: |
    - name: Camunda BPM Platform Chart
      url: https://github.com/camunda-community-hub/camunda-helm/tree/main/charts/camunda-bpm-platform
    - name: Camunda BPM Platform Docker
      url: https://github.com/camunda/docker-camunda-bpm-platform
    - name: Camunda BPM Platform
      url: https://github.com/camunda/camunda-bpm-platform
  # This is will be generated automatically by the release workflow.
  artifacthub.io/changes: |
    - kind: added
      description: "Add option to customize deployment using extra env vars"
